### PR TITLE
22 show waiting screen

### LINKED ISSUE #22: show waiting screen after player joins a game
- requires #51 

# observe waiting screen

- [x] create list of joined players 
- [x] when tagger is chosen, indicate with highlighted player tile 
- [x] create quit button
  - [x] on tap, show are you sure dialog
    - [x] redirect to lobby on tap yes
    - [x] navigator pop on no

player find and join a game - 4
player find and join a game - 5
player find and join a game - 6

### PR DESCRIPTION
**Pull request by tamari-gray**
fixes #22 

@nickmeinhold theres a broken test in here that i think will be easy to solve after we transition to navigating from the navigation service. 
No rush to look at this pr, im keen to hack out the nav service issue + gmaps before coming back to this.

when you get to this i hope its a smoother review then normal 😄 

waiting on: 
- [x] #58 Allow adding maps to widgets 
- [x] #82 Use NavigationService for all navigation

### CODE REVIEW

**Comment by nickmeinhold** [comment]
OK cool as, thanks for the info on the priority order, that's really helpful 👍

**Comment by nickmeinhold** [comment]
@tamari-gray this PR currently is requesting review - if it's a WIP, could you maybe convert to a draft?  I keep seeing it and coming back to read through and realise it's not waiting for review.  Thanks! :-)

**Comment by tamari-gray** [comment]
Alg!

**Comment by tamari-gray** [comment]
now waiting on #122

**Review by tamari-gray — COMMENTED** [review]
looks good

**Pull request merged**
