### PR TITLE
primary variant color accessible

### LINKED ISSUE #8: setup custom theme (light mode only)
problem: get primary variant color in accesssible place

### PR DESCRIPTION
**Pull request by tamari-gray**
fixes #8

### CODE REVIEW

**Review by nickmeinhold — COMMENTED** [review]
Nice one mate! I'm thinking this would make more sense as a static method or maybe even an enum (although you'd have to use a 3rd party enum package to get enum classes as the native dart enums aren't very powerful and I don't think would work here) - what do you think?  In this case the object on the left of obj.func() or obj.getter isn't used to get the return value.  Sorry if I'm not making sense, feel free to get a zoom going if you'd like

**Comment by nickmeinhold** [comment]
Static extension functions are a bit weird - you can do it but the static function is part of the extension class, not the class being extended - so in your case it would be `CustomColorScheme.variant` rather than `ColorScheme.variant`

**Comment by tamari-gray** [comment]
@nickmeinhold ready for another review

**Review by nickmeinhold — APPROVED** [review]
Looks great man!

**Pull request merged**
