### PR TITLE
3 welcome screen

### LINKED ISSUE #3: welcome screen
- [x] copy widgets from adobe
- [x] navigate to sign in screen and create account screen

### PR DESCRIPTION
**Pull request by tamari-gray**
sorry for the delay nick! 

anything you think i could do better or any changes you think might help please let me know.

lets get this project cracking!!

### CODE REVIEW

**Review by nickmeinhold — APPROVED** [review]
Awesome work mate!!  I love the test with the navigator observer - getting some sweet tests in from the beginning, that's impressive!

**Comment by nickmeinhold** [comment]
I tested on iOS - looks great! 
Screen Shot 2020-08-03 at 2 45 09 am

Woohoo! Let's do this!

**Comment by nickmeinhold** [comment]
Do you want the reviewer to merge?  Or leave the author to merge?  In the chat app we were leaving the author to merge, although I think it's more common for the reviewer to merge, I think leaving it for the author to merge has its benefits.  Whatever feels right to you is the way to go I reckon.

**Comment by tamari-gray** [comment]
thanks nick!! I like having the reviwer to merge primarily. and the author merge just if the reviewer is out for the day or something. 
Not too fussed over it :) 
thanks for trying it out on ios too, glad too know it works on there :)

**Pull request merged**
